---
# This playbook is used for provisioning of gce/vm-image, gce/vm-replica, and vagrant
# To execute it directly to a running machine, just use this command with the ip:
# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u solo -i '1.2.3.4,' ansible-playbook.yml -v

- hosts: all
  remote_user: solo
  become: yes
  become_user: root
  become_method: sudo
  vars:
    reboot_vm_machine: yes # reboot machine at the end of the playbook
    terminal_custom_title: "solo.io workshops"
    vagrant: no
    provision: yes

  roles:
    - role: vagrant
      when: vagrant | bool
    - role: repo
      repo_name: workshops
      repo_branch: master
    - role: license
    - role: k9s
      when: provision | bool
    - role: software_install
      when: provision | bool
    - role: vm_configuration
      reboot_vm: '{{ reboot_vm_machine | bool }}'
      terminal_title: '{{ terminal_custom_title }}'
      when: provision | bool

  tasks:
  - name: Print parameters
    debug:
      msg: 'reboot_vm={{ reboot_vm_machine | bool }} terminal_title={{ terminal_custom_title }} provision={{ provision }}'
