---
# This playbook is used for provisioning of gce/vm-image, gce/vm-replica, and vagrant
# To execute it directly to a running machine, just use this command with the ip:
# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u solo -i '1.2.3.4,' ansible-playbook.yml -v

- hosts: all
  remote_user: solo
  become: yes
  become_user: root
  become_method: sudo
  vars:
    reboot_vm: yes # reboot machine at the end of the playbook
    terminal_title: "solo.io workshops"

  roles:
    - role: repo
      repo_name: workshops
      repo_branch: master
    - role: k9s
    - role: software_install
    - role: vm_configuration
      reboot_vm: '{{ reboot_vm | bool }}'
      terminal_title: '{{ terminal_title | bool }}'

  tasks:
  - name: Print parameters
    debug:
      msg: 'reboot_vm={{ reboot_vm | bool }} terminal_title={{ terminal_title }}'

