---
- hosts: all
  remote_user: solo
  become: yes
  become_user: root
  become_method: sudo
  vars:
    reboot_vm: yes # reboot machine at the end of the playbook
    reset_repo: no # force overwrite of local changes
    terminal_title: "solo.io workshops"

  roles:
    - role: repo
      repo_name: workshops
      force: '{{ reset_repo | bool }}'
    - role: k9s
    - role: software_install
    - role: vm_configuration
      reboot_vm: '{{ reboot_vm | bool }}'
      terminal_title: '{{ terminal_title | bool }}'

  tasks:
  - name: Print parameters
    debug:
      msg: 'reboot_vm={{ reboot_vm | bool }} reset_repo={{ reset_repo | bool }} terminal_title={{ terminal_title }}'

