---
- name: Check the repo folder has been already cloned
  stat:
    path: /home/solo/{{ repo_name }}
  register: workshop_folder

- name: Clone of master branch
  git:
    repo: https://github.com/solo-io/{{ repo_name }}.git
    dest: /home/solo/{{ repo_name }}
    single_branch: yes
    depth: 1
    version: '{{ repo_branch }}'
  environment:
    GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
  become: yes
  become_user: solo
  become_method: sudo
